### ISSUE TITLE
Where is cfg files?

### ISSUE THREAD

**Issue by gyunt** [cm-jones/thales#1]
I believe the project is currently a work in progress.

The cfg files mentioned in the README.md are missing.

Regardless, I'm quite interested in this project. 
As far as I know, there are no public option trading frameworks available.

**Comment by cm-jones** [comment]
Thanks for your interest in the project.

Yes, it is currently a work in progress. I hope to have it working in a few weeks or so.

You'll eventually find the relevant config files under the config directory.
